name: pocketgenie
description: "AI-Powered Mobile Productivity Assistant"
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Navigation
  cupertino_icons: ^1.0.2
  go_router: ^12.0.0
  provider: ^6.0.0

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sqflite: ^2.3.0
  path_provider: ^2.1.0

  # HTTP & API
  http: ^1.1.0
  dio: ^5.3.0

  # JSON Serialization
  json_serializable: ^6.7.0
  json_annotation: ^4.8.1

  # State Management
  riverpod: ^2.4.0
  riverpod_generator: ^2.3.0

  # Notifications
  flutter_local_notifications: ^16.1.0

  # Date & Time
  intl: ^0.19.0

  # Voice Input
  speech_to_text: ^6.3.0
  permission_handler: ^11.4.0

  # PDF Export
  pdf: ^3.10.0
  printing: ^5.11.0

  # CSV Export
  csv: ^5.1.0

  # Utilities
  uuid: ^4.0.0
  logger: ^2.0.0
  connectivity_plus: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.0
  hive_generator: ^2.0.0
  riverpod_generator: ^2.3.0
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic

